import 'package:autonomy_flutter/nft_collection/models/models.dart';

extension AssetExt on Asset {
  // copyWith method
  Asset copyWith({
    String? indexID,
    String? thumbnailID,
    DateTime? lastRefreshedTime,
    String? artistID,
    String? artistName,
    String? artistURL,
    String? artists,
    String? assetID,
    String? title,
    String? description,
    String? mimeType,
    String? medium,
    int? maxEdition,
    String? source,
    String? sourceURL,
    String? previewURL,
    String? thumbnailURL,
    String? galleryThumbnailURL,
    String? assetData,
    String? assetURL,
    bool? isFeralfileFrame,
    String? initialSaleModel,
    String? originalFileURL,
    String? artworkMetadata,
  }) =>
      Asset(
        indexID: indexID ?? this.indexID,
        thumbnailID: thumbnailID ?? this.thumbnailID,
        lastRefreshedTime: lastRefreshedTime ?? this.lastRefreshedTime,
        artistID: artistID ?? this.artistID,
        artistName: artistName ?? this.artistName,
        artistURL: artistURL ?? this.artistURL,
        artists: artists ?? this.artists,
        assetID: assetID ?? this.assetID,
        title: title ?? this.title,
        description: description ?? this.description,
        mimeType: mimeType ?? this.mimeType,
        medium: medium ?? this.medium,
        maxEdition: maxEdition ?? this.maxEdition,
        source: source ?? this.source,
        sourceURL: sourceURL ?? this.sourceURL,
        previewURL: previewURL ?? this.previewURL,
        thumbnailURL: thumbnailURL ?? this.thumbnailURL,
        galleryThumbnailURL: galleryThumbnailURL ?? this.galleryThumbnailURL,
        assetData: assetData ?? this.assetData,
        assetURL: assetURL ?? this.assetURL,
        initialSaleModel: initialSaleModel ?? this.initialSaleModel,
        originalFileURL: originalFileURL ?? this.originalFileURL,
        isFeralfileFrame: isFeralfileFrame ?? this.isFeralfileFrame,
        artworkMetadata: artworkMetadata ?? this.artworkMetadata,
      );
}
